templates:
  default: &template_default
    build:
      upfront: 0.1
      duration:
        function: linear
        coefs:
          a: 10
          b: 0
      costs:
        mineral:
          function: linear
          coefs:
            a: 0
            b: 100
    consumes: {}
    prods: {}
    stores: {}
    wastes: {}
    manpower:
      min:
        function: linear
        coefs:
          b: 100_000
      optimal:
        function: linear
        coefs:
          b: 1_000_000
      max:
        function: linear
        coefs:
          b: 10_000_000

items:

  e_plant:
    <<: *template_default
    title: Energy plant
    description: Energy grid that produce energy using nuclear isotops, sun, wind, and fossil fuel, and also can fill energy storage means with chemistery.
    prods:
      energy:
        function: linear
        coefs:
          a: 10
    wastes:
      pollution:
        function: linear
        coefs:
          a: 0.5

  mine:
    <<: *template_default
    title: Mines
    description: Mines are a polluting industry that can generate tons of basic ressources required for most of the industry. Network of mines generate it's own cheminals.
    consumes:
      energy:
        function: linear
        coefs:
          a: 1
      chemical:
        function: linear
        coefs:
          a: 0.1
    prods:
      mineral:
        function: linear
        coefs:
          a: 10
      chemical:
        function: linear
        coefs:
          a: 0.1
    wastes:
      pollution:
        function: linear
        coefs:
          a: 1

  agrifood:
    <<: *template_default
    title: Farmed lands
    description: Large portions of the land space is used to produce nutrient. It growth crops, animal farms, etc. using standard mechanized tools and vehicules. Food can then be distributed via a dense network of distributors.
    consumes:
      mineral:
        function: linear
        coefs:
          a: 0.2
      energy:
        function: linear
        coefs:
          a: 0.2
    prods:
      food:
        function: linear
        coefs:
          a: 10
    wastes:
      pollution:
        function: linear
        coefs:
          a: 0.1

  # mine2:
  #   <<: *template_default
  #   title: Specialized deep mines
  #   description: These mines are deeper and is using robots to extract new materials
  # a2_plant:
  #   <<: *template_default
  #   title: Meta-material furnaces
  # c_plant:
  #   <<: *template_default
  #   title: Chemical plant
  # w_plant:
  #   <<: *template_default
  #   title: Weapon assembly
  # l_plant:
  #   <<: *template_default
  #   title: Logistic assembly
  #   description: An assembly site that make trunks, trains, planes, and civilan space transports
